### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by fergald** [jackbsteinberg/get-originals-rewriter#74]
I checked out 29e2a7bea2f7b4543974a4eb1484afd5654887ed and ran tests and got this failure

```
$@ npm test

> get-originals-rewriter@1.0.0-pre test /home/fergal/github/jackbsteinberg/get-originals-rewriter
> jest

 FAIL  ./test.js
  ● Test suite failed to run

    TypeError: Illegal constructor

    > 1 | const a = new Element();
        | ^
      2 | 
      3 | console.log(a.children[1].nextSibling.previousSibling);
      4 | 

      at new Element (node_modules/jsdom/lib/jsdom/living/generated/Element.js:15:9)
      at Object.<anonymous> (test.js:1:1)

 PASS  lib/__tests__/test.js (31.33s)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       16 passed, 16 total
Snapshots:   0 total
Time:        32.07s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by fergald** [comment]
Nevermind, there was a file in my directory names test.js and I guess jest decided to run it. Hmm.
